### ISSUE TITLE
Reference "ftrace hook" website return 404

### ISSUE THREAD

**Issue by Yatogaii** [hahaleyile/ucas_rootkit#1]

**Comment by hahaleyile** [comment]
where is the reference of "ftrace hook"

**Comment by Yatogaii** [comment]
here, 
```
参考资料

    ftrace hook [Using ftrace to hook to functions](https://01.org/linuxgraphics/gfx-docs/drm/trace/ftrace-uses.html)
```

**Comment by hahaleyile** [comment]
> here,
> 
> ```
> 参考资料
> 
>     ftrace hook [Using ftrace to hook to functions](https://01.org/linuxgraphics/gfx-docs/drm/trace/ftrace-uses.html)
> ```

翻墙 😠
